# Generated by Django 4.2.29 on 2026-03-10 06:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="校区名称"),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=255, verbose_name="位置"),
                ),
                ("latitude", models.FloatField(default=31.2304, verbose_name="纬度")),
                ("longitude", models.FloatField(default=121.4737, verbose_name="经度")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
            ],
            options={
                "verbose_name": "校区",
                "verbose_name_plural": "校区",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("system", "系统"),
                            ("weather", "天气"),
                            ("schedule", "排程"),
                        ],
                        default="system",
                        max_length=20,
                        verbose_name="通知类型",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="是否已读")),
            ],
            options={
                "verbose_name": "系统通知",
                "verbose_name_plural": "系统通知",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SportEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="项目名称"),
                ),
                (
                    "suitable_temp_min",
                    models.IntegerField(default=12, verbose_name="适宜最低温"),
                ),
                (
                    "suitable_temp_max",
                    models.IntegerField(default=28, verbose_name="适宜最高温"),
                ),
                ("avoid_rain", models.BooleanField(default=True, verbose_name="是否避雨")),
                (
                    "avoid_wind_level",
                    models.FloatField(default=8.0, verbose_name="最大适宜风速"),
                ),
                (
                    "intensity",
                    models.CharField(
                        choices=[("low", "低强度"), ("medium", "中强度"), ("high", "高强度")],
                        default="medium",
                        max_length=20,
                        verbose_name="强度",
                    ),
                ),
                (
                    "calories_per_hour",
                    models.PositiveIntegerField(default=300, verbose_name="每小时热量消耗"),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
            ],
            options={
                "verbose_name": "运动项目",
                "verbose_name_plural": "运动项目",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="WeatherAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="预警标题")),
                (
                    "level",
                    models.CharField(
                        choices=[("info", "提示"), ("warning", "警告"), ("danger", "危险")],
                        default="info",
                        max_length=20,
                        verbose_name="预警级别",
                    ),
                ),
                ("message", models.TextField(verbose_name="预警内容")),
                (
                    "alert_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="预警时间"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="是否有效")),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="core.campus",
                        verbose_name="校区",
                    ),
                ),
            ],
            options={
                "verbose_name": "天气预警",
                "verbose_name_plural": "天气预警",
                "ordering": ["-alert_time"],
            },
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="场地名称")),
                ("venue_type", models.CharField(max_length=100, verbose_name="场地类型")),
                (
                    "capacity",
                    models.PositiveIntegerField(default=50, verbose_name="容量"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "可用"),
                            ("maintenance", "维护中"),
                            ("closed", "关闭"),
                        ],
                        default="available",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("indoor", models.BooleanField(default=False, verbose_name="是否室内")),
                (
                    "has_lighting",
                    models.BooleanField(default=False, verbose_name="是否有照明"),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="venues",
                        to="core.campus",
                        verbose_name="所属校区",
                    ),
                ),
            ],
            options={
                "verbose_name": "场地",
                "verbose_name_plural": "场地",
                "ordering": ["campus_id", "id"],
            },
        ),
        migrations.CreateModel(
            name="Suggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("suggest_date", models.DateField(verbose_name="推荐日期")),
                ("suggest_time", models.TimeField(verbose_name="推荐时间")),
                ("score", models.FloatField(default=0, verbose_name="推荐分数")),
                (
                    "weather_summary",
                    models.CharField(blank=True, max_length=255, verbose_name="天气概述"),
                ),
                ("reason", models.TextField(blank=True, verbose_name="推荐原因")),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggestions",
                        to="core.campus",
                        verbose_name="校区",
                    ),
                ),
                (
                    "sport_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggestions",
                        to="core.sportevent",
                        verbose_name="运动项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "智能建议",
                "verbose_name_plural": "智能建议",
                "ordering": ["-score", "suggest_date", "suggest_time"],
            },
        ),
        migrations.CreateModel(
            name="Meet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="活动名称")),
                (
                    "expected_people",
                    models.PositiveIntegerField(default=20, verbose_name="预计人数"),
                ),
                ("planned_date", models.DateField(verbose_name="计划日期")),
                ("planned_start_time", models.TimeField(verbose_name="计划开始时间")),
                ("planned_end_time", models.TimeField(verbose_name="计划结束时间")),
                (
                    "organizer",
                    models.CharField(blank=True, max_length=100, verbose_name="组织者"),
                ),
                (
                    "contact",
                    models.CharField(blank=True, max_length=50, verbose_name="联系方式"),
                ),
                ("note", models.TextField(blank=True, verbose_name="备注")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待安排"),
                            ("scheduled", "已排程"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meets",
                        to="core.campus",
                        verbose_name="校区",
                    ),
                ),
                (
                    "sport_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meets",
                        to="core.sportevent",
                        verbose_name="运动项目",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meets",
                        to="core.venue",
                        verbose_name="场地",
                    ),
                ),
            ],
            options={
                "verbose_name": "活动/比赛",
                "verbose_name_plural": "活动/比赛",
                "ordering": ["-planned_date", "planned_start_time"],
            },
        ),
        migrations.CreateModel(
            name="FinalSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("scheduled_date", models.DateField(verbose_name="排程日期")),
                ("scheduled_start_time", models.TimeField(verbose_name="开始时间")),
                ("scheduled_end_time", models.TimeField(verbose_name="结束时间")),
                (
                    "weather_risk",
                    models.CharField(default="低", max_length=50, verbose_name="天气风险"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="说明")),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="final_schedules",
                        to="core.campus",
                        verbose_name="校区",
                    ),
                ),
                (
                    "meet",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="final_schedule",
                        to="core.meet",
                        verbose_name="活动",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.venue",
                        verbose_name="场地",
                    ),
                ),
            ],
            options={
                "verbose_name": "最终排程",
                "verbose_name_plural": "最终排程",
                "ordering": ["-scheduled_date", "scheduled_start_time"],
            },
        ),
        migrations.CreateModel(
            name="WeatherRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("forecast_time", models.DateTimeField(verbose_name="预报时间")),
                ("temperature", models.FloatField(default=0, verbose_name="温度")),
                (
                    "apparent_temperature",
                    models.FloatField(default=0, verbose_name="体感温度"),
                ),
                ("humidity", models.FloatField(default=0, verbose_name="湿度")),
                ("precipitation", models.FloatField(default=0, verbose_name="降水")),
                ("wind_speed", models.FloatField(default=0, verbose_name="风速")),
                ("weather_code", models.IntegerField(default=0, verbose_name="天气编码")),
                ("is_day", models.BooleanField(default=True, verbose_name="是否白天")),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_records",
                        to="core.campus",
                        verbose_name="校区",
                    ),
                ),
            ],
            options={
                "verbose_name": "天气记录",
                "verbose_name_plural": "天气记录",
                "ordering": ["forecast_time"],
                "unique_together": {("campus", "forecast_time")},
            },
        ),
    ]
