# Generated by Django 4.2.29 on 2026-04-27 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_userprofile_operationlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("content", models.TextField(verbose_name="反馈内容")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "待处理"), ("processed", "已处理")],
                        default="pending",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
                ("reply", models.TextField(blank=True, verbose_name="处理回复")),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_feedbacks",
                        to="core.campus",
                        verbose_name="校区",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_feedbacks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="学生",
                    ),
                ),
                (
                    "weather_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedbacks",
                        to="core.weatherrecord",
                        verbose_name="天气记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "天气反馈",
                "verbose_name_plural": "天气反馈",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VenueFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("content", models.TextField(verbose_name="反馈内容")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "待处理"), ("processed", "已处理")],
                        default="pending",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
                ("reply", models.TextField(blank=True, verbose_name="处理回复")),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="venue_feedbacks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="学生",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="core.venue",
                        verbose_name="场地",
                    ),
                ),
            ],
            options={
                "verbose_name": "场地反馈",
                "verbose_name_plural": "场地反馈",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ActivityRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("registered", "已报名"), ("cancelled", "已取消")],
                        default="registered",
                        max_length=20,
                        verbose_name="报名状态",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="备注")),
                (
                    "meet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="core.meet",
                        verbose_name="活动",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_registrations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="学生",
                    ),
                ),
            ],
            options={
                "verbose_name": "活动报名",
                "verbose_name_plural": "活动报名",
                "ordering": ["-created_at"],
                "unique_together": {("student", "meet")},
            },
        ),
    ]
