# Generated by Django 4.2.29 on 2026-04-27 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0003_weatherfeedback_venuefeedback_activityregistration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activityregistration",
            name="note",
        ),
        migrations.AddField(
            model_name="activityregistration",
            name="apply_reason",
            field=models.TextField(blank=True, verbose_name="报名备注"),
        ),
        migrations.AddField(
            model_name="activityregistration",
            name="review_reason",
            field=models.TextField(blank=True, verbose_name="审核意见"),
        ),
        migrations.AddField(
            model_name="activityregistration",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="审核时间"),
        ),
        migrations.AddField(
            model_name="activityregistration",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_registrations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="审核人",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_notifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="发送人",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="接收用户",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="related_meet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="core.meet",
                verbose_name="关联活动",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="source_module",
            field=models.CharField(blank=True, max_length=50, verbose_name="来源模块"),
        ),
        migrations.AddField(
            model_name="notification",
            name="target_role",
            field=models.CharField(blank=True, max_length=20, verbose_name="接收角色"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_generate_schedule",
            field=models.BooleanField(default=False, verbose_name="教师-生成智能排程"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_generate_suggestions",
            field=models.BooleanField(default=False, verbose_name="教师-生成智能建议"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_manage_feedback",
            field=models.BooleanField(default=False, verbose_name="教师-反馈处理"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_manage_meets",
            field=models.BooleanField(default=False, verbose_name="教师-活动管理"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_manage_registrations",
            field=models.BooleanField(default=False, verbose_name="教师-报名审核"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_register_activity",
            field=models.BooleanField(default=True, verbose_name="学生-活动报名"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_send_notifications",
            field=models.BooleanField(default=False, verbose_name="教师-发布通知"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_submit_feedback",
            field=models.BooleanField(default=True, verbose_name="学生-提交反馈"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_view_alerts",
            field=models.BooleanField(default=True, verbose_name="学生-查看预警"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_view_own_notifications",
            field=models.BooleanField(default=True, verbose_name="学生-查看个人通知"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_view_schedule",
            field=models.BooleanField(default=True, verbose_name="学生-查看排程"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_view_statistics",
            field=models.BooleanField(default=False, verbose_name="教师-查看统计分析"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_view_suggestions",
            field=models.BooleanField(default=True, verbose_name="学生-查看智能建议"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_view_weather",
            field=models.BooleanField(default=True, verbose_name="学生-查看天气"),
        ),
        migrations.AlterField(
            model_name="activityregistration",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待审核"),
                    ("approved", "已批准"),
                    ("rejected", "未通过"),
                    ("cancelled", "已取消"),
                ],
                default="pending",
                max_length=20,
                verbose_name="报名状态",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("registration", "活动报名"),
                    ("feedback", "反馈处理"),
                    ("weather", "天气"),
                    ("schedule", "排程"),
                    ("suggestion", "智能建议"),
                    ("system", "系统"),
                ],
                default="system",
                max_length=20,
                verbose_name="通知类型",
            ),
        ),
        migrations.CreateModel(
            name="NotificationRead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("is_read", models.BooleanField(default=False)),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_records",
                        to="core.notification",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_reads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "notification")},
            },
        ),
    ]
