# Generated by Django 4.2.29 on 2026-04-29 13:16

from django.db import migrations, models


def backfill_activity_duration(apps, schema_editor):
    Meet = apps.get_model("core", "Meet")
    for meet in Meet.objects.all():
        minutes = 60
        if meet.planned_start_time and meet.planned_end_time:
            start_mins = meet.planned_start_time.hour * 60 + meet.planned_start_time.minute
            end_mins = meet.planned_end_time.hour * 60 + meet.planned_end_time.minute
            delta = end_mins - start_mins
            if delta > 0:
                minutes = delta
        meet.activity_duration_minutes = minutes
        meet.save(update_fields=["activity_duration_minutes"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_activityregistration_note_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meet",
            name="activity_duration_minutes",
            field=models.PositiveIntegerField(
                default=60, verbose_name="活动总时长（分钟）"
            ),
        ),
        migrations.AlterField(
            model_name="meet",
            name="planned_date",
            field=models.DateField(blank=True, null=True, verbose_name="原计划日期"),
        ),
        migrations.AlterField(
            model_name="meet",
            name="planned_end_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="原计划结束时间"
            ),
        ),
        migrations.AlterField(
            model_name="meet",
            name="planned_start_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="原计划开始时间"
            ),
        ),
        migrations.RunPython(backfill_activity_duration, migrations.RunPython.noop),
    ]
